version: "3.8"

services:
  db-microservices:
    image: postgres:15
    container_name: postgres_db_microservices-two
    restart: unless-stopped
    environment:
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
      POSTGRES_DB: microservicesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata-microservices-recipes:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  client-gateway:
    depends_on: 
      - db-microservices
      - kafka
    build: ./client-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

  auth-ms:
    depends_on:
      - db-microservices
    build: ./ms-auth
    volumes:
      - ./ms-auth/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_SECRET=secret
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb
      
  products-ms:
    depends_on: 
      - db-microservices
    build: ./ms-products
    volumes:
      - ./ms-products/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb

  recipe-ms:
    depends_on: 
      - db-microservices
    build: ./ms-recipe
    volumes:
      - ./ms-recipe/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb

  client-ms:
    depends_on: 
      - db-microservices
    build: ./ms-client
    volumes:
      - ./ms-client/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb

  review-ms:
    depends_on: 
      - db-microservices
    build: ./ms-review
    volumes:
      - ./ms-review/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb
  
  planType-ms:
    depends_on: 
      - db-microservices
    build: ./ms-plan-type
    volumes:
      - ./ms-plan-type/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb
  

volumes:
  pgdata-microservices-recipes: